config/routes.rb
Rails.application.routes.draw do

  get 'homes/index'
  get '/thankyou', to: "feedbacks#thankyou"
  get '/thank_you', to: "housing_rentals#thank_you"

  devise_for :users, skip: :registrations
  resources :housing_rentals
  resources :loans
  resources :feedbacks

  resources :loans do
    collection { post :import }
  end

  authenticate :user do
    resources :feedbacks, only: [:index, :edit, :update, :destroy]
  end
  root "loans#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
  
  before_validation :get_id, on: :create


  scope :closed_status, -> { where(:status => 0) }
  scope :opened_status, -> { where(:status => 1) }
  scope :follow_status, -> { where(:status => 2) }

  scope :today, -> { where(:created_at => Date.today)}
  scope :day_wise, -> { where("? BETWEEN startDate AND endDate", Date.today)}

  enum status: [:closed, :opened, :follow_up]
  ENUM_ENTITY = {"closed" => 0, "opened" => 1, "follow up" => 2}
 
  def self.search(search)
  	where('name LIKE :search OR email LIKE :search OR contact_no LIKE :search OR reference LIKE :search', search: "%#{search}%")
  end

  def get_id
    @id = Loan.all
    @last =  @id.ids.last
    if @last.nil?
      a = 1
	  self.reference =  "FYL000#{a}" if self.reference.blank?
    else
      a = @last + 1 
      self.reference =  "FYL000#{a}" if self.reference.blank?
    end
  end

#Export and Import Configuration

  def self.to_csv(fields = column_names, options = {})
    CSV.generate(options) do |csv|
      csv << fields
      all.each do |loan|
        csv << loan.attributes.values_at(*fields)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      loan_hash = row.to_hash
      loan = find_or_create_by!(name: loan_hash['name'],contact_no: loan_hash['contact_no'], email: loan_hash['email'], profession: loan_hash['profession'], salary: loan_hash['salary'], obligation: loan_hash['obligation'], status: loan_hash['status'],loan_amount: loan_hash['loan_amount'], remarks: loan_hash['remarks'])
      loan.update_attributes(loan_hash)
    end
  end


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!

  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  
  # after_action :get_id, on: :create

  def index
    loans = Loan.search(params[:search])
    loans = Loan.closed_status if params[:search] == "closed_status"
    loans = Loan.opened_status if params[:search] == "opened_status"
    loans = Loan.follow_status if params[:search] == "follow_status"
    loans = Loan.day_wise if params[:search] == "day_wise"
    loans = Loan.all if params[:search].nil?
    @loans = loans.paginate(page: params[:page]).order("created_at DESC").per_page(10)
    respond_to do |format|
    format.html
    format.csv {send_data @loans.to_csv(['name', 'contact_no', 'email', 'profession', 'salary', 'obligation', 'status', 'loan_amount', 'remarks'])}
    # format.json {render json: @loan, status: :ok}
    end 
  end

  def import
    Loan.import(params[:file])
    redirect_to root_path, notice: "Lead Loans Imported."
  end

  def new
    @loan = Loan.new
  end

  def create
    user_id = current_user.id
    @loan_created = Loan.new(name: params[:loan][:name],
     contact_no: params[:loan][:contact_no], email: params[:loan][:email],
      loan_amount: params[:loan][:loan_amount],
       status: params[:status].to_i, profession: params[:loan][:profession],
        salary: params[:loan][:salary], remarks: params[:loan][:remarks],
         obligation: params[:loan][:obligation], loan_amount: params[:loan][:loan_amount])
    @loan_created.user_id = user_id
    respond_to do |format|
      if @loan_created.save
      format.json {render json: @loan_created, status: :created}
      format.js
      format.html {redirect_to root_path, flash: {success: "Loan was successfully created."}}
      else
      format.json {render json: @loan_created.errors.full_messages, status: :unprocessable_entity}
      format.js
      format.html {redirect_to loans_path, flash: {error: @loan_created.errors.full_messages}}
      end
    end
  end


  def show
  end

  def edit
    @loan  = Loan.find(params[:id])
  end

  def update
    respond_to do |format|
      if @loan.update(name: params[:loan][:name],
     contact_no: params[:loan][:contact_no], email: params[:loan][:email],
      loan_amount: params[:loan][:loan_amount],
       status: params[:status].to_i, profession: params[:loan][:profession],
        salary: params[:loan][:salary], remarks: params[:loan][:remarks],
         obligation: params[:loan][:obligation], loan_amount: params[:loan][:loan_amount])
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_loan
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(:name, :contact_no, :email, :loan_amount, :pstatus, :profession, :salary, :remarks, :obligation)
    end


    def get_id
      # @id = Loan.all
      # @loan_id = @id.ids.last
      # p @loan_id
      self.reference =  "FYL/000" if self.reference.blank?

    end

end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_action_button.html.erb
<div class="row action-button-margins">
    <div class="col-md-2">
      <button type="button" class= "btn btn-outline-primary btn-md" data-toggle="modal" data-target="#ModalAddFinance">Add new lead</button>
    </div>
    <div class="col-md-2">
      <%= link_to "Feedbacks", feedbacks_path, class: "btn btn-outline-primary"%>
    </div>
    
    <div class="dropdown">
      <button onclick="myFunction()" id="dropbtn" class= "btn btn-outline-primary btn-md"">Sort By</button>
        <div id="myDropdown" class="dropdown-content">
          <%= link_to 'Closed', loans_path(search: "closed_status") %>
          <%= link_to 'Opened', loans_path(search: "opened_status")%>
          <%= link_to 'Follow', loans_path(search: "follow_status")%>
        </div>
    </div>

    <div class="col-md-2">
      <%= link_to "All Lead", root_path, class: "btn btn-outline-primary btn-md" %>
    </div>

  
    <div class="col-md-2">
       <%= form_tag import_loans_path, multipart: true, class: 'form-inline' do %>
        <div class="form-group">
          <%= link_to "Export CSV", loans_path(format: "csv"), class: 'btn btn-outline-success btn-md' %>
        </div>
        <!-- <div class="form-group">
          <%#= file_field_tag :file, class: '' %>
        </div> -->
        
        <!-- <div class="form-group"> -->
          <%#= submit_tag "CSV", class: 'btn btn-info' %>
        <!-- </div> -->
      <% end %>
    </div>


    <div class="col-3">
      <%= form_tag(loans_path, method: :get) do %>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "search name, mobile no " %>
        <%#= submit_tag 'Search', name: nil ,class: "btn btn-outline-primary btn-md" %>
      <% end %>
    </div> 

    <div class="col-md-10">
      <div class="full-left">
        <% if user_signed_in?%>
          <span class="user"><%= current_user.email %></span> |
              <%#= link_to "Change Password", edit_user_registration_path %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <% end %>
      </div>
    </div>


</div>


<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Loan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%= render "form2" %>
      </div>
    </div>
  </div>
</div>



<style type="text/css">
  ul {list-style: none;padding: 0px;margin: 0px;}
  ul li {display: block;position: relative;float: left;border:1px solid #fff}
  li ul {display: none;}
  ul li a {display: block;background: #fff;padding: 5px 10px 5px 10px;text-decoration: none;
           white-space: nowrap;color: #fff;}
  ul li a:hover {background: #fff;}
  li:hover ul {display: block; position: absolute;}
  li:hover li {float: none;}
  li:hover a {background: #b9b9b9;}
  li:hover li a:hover {background: #0275d8;}
  #drop-nav li ul li {border-top: 0px;}
  .email{
    padding-top: 1%;
  }
  .hi{
    color: black;
    background-color: #94a294;
  }
  .user{
    background-color: orange;
    font-size: 20px;

  }
  .full-left{
        width: 99%;
    float: right;
    margin-top: -8%;
}
  }
</style>









<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
        if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
        } else {
            a[i].style.display = "none";
        }
    }
}
</script>




<style type="text/css">
  <style>
#dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

#dropbtn:hover, #dropbtn:focus {
    background-color: #3e8e41;
}

#myInput {
    border-box: box-sizing;
    background-image: url('searchicon.png');
    background-position: 14px 12px;
    background-repeat: no-repeat;
    font-size: 16px;
    padding: 14px 20px 12px 45px;
    border: none;
    border-bottom: 1px solid #ddd;
}

#myInput:focus {outline: 3px solid #ddd;}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f6f6f6;
    min-width: 230px;
    overflow: auto;
    border: 1px solid #ddd;
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>
</style>

app/views/loans/_form2.html.erb
<%= form_for (:loan), html: {class: 'finance_form'}, method: :post, remote: true do |f| %>
  

  <div class="form-group row">
    <%= f.label :name, "Customer Name:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :contact_no, "Contact No:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :contact_no, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
   <%= f.label :email, "Email:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :email, required: true, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :loan_amount, "Loan Amount:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.number_field :loan_amount, required: true, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :salary, "Salary:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.number_field :salary, required: true, class: 'form-control', min: 0 %>
   </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :obligation, "Obligation:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :obligation, required: true, class: 'form-control' %>
   </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :profession, "Profession:", class: "col-4 col-form-label" %>
   <% profession = ['Self Emp1', 'Self Emp2']%>
   <div class="col-8">
     <%= f.select :profession, profession, required: true, class: 'form-control', prompt: "select" %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :status, "Status:", class: "col-4 col-form-label" %>
   <div class="col-8">
    <%#= f.select :status,  options_from_collection_for_select(Loan::ENUM_ENTITY, :last, :first ), { :prompt => "select"}, {selected: true} %>
    <%= select_tag :status,  options_from_collection_for_select(Loan::ENUM_ENTITY, :last, :first ), { :prompt => "Select Status"} %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :remarks, "Remarks:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_area :remarks, required: true, class: 'form-control' %>
   </div>
  </div>


  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary pull-right'  %>
  </div>

<% end %>

app/views/loans/_nav.html.erb
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand'>Test</a>
            <ul class='nav'>
                <li><a>Item 1</a></li>
                <li><a>Item 2</a></li>
            </ul>
            <form class="navbar-search pull-left">
                <div class='input-prepend'>
                    <select style="width: 80px">
                        <option>People </option>
                        <option>Model</option>
                        <option>Make</option>
                        <select>
                    <input/ > 
                    <button type="submit" class="btn">Search</button>
                </div>
                
              
                
            </form>
        </div>
    </div>
</div>


<style type="text/css">
    .navbar-search {
  margin-top: 4px;
}

.navbar .btn, .navbar .btn-group {
  margin-top: 1px;
}

.navbar-search select {
  position: relative;
  left: 84px;
  z-index: 99;
}

.navbar-search input {
  padding-left: 84px;
}

.navbar-search select,
.navbar-search input {
margin-bottom: 0px;
}
</style>

app/views/loans/_table.html.erb
<div class="table_invoice">
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr class="bg-primary">
        <th class="align_center">Ref ID</th>
        <th class="align_center">Name</th>
        <th class="align_center">Mobile No</th>
        <th class='align_center'>Email</th>
        <th class='align_center'>Profession</th>
        <th class='align_center'>Salary</th>
        <th class='align_center'>Obligation</th>
        <th class='align_center'>Status</th>
        <th class='align_center'>Loan Amount</th>
        <th class='align_center'>Remarks</th>
        <th class='align_center'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @loans.each do |loan| %>
      <tr>
        <td class="align_center">
          <%= loan.reference %>
        </td>
        <td class="align_center">
          <%= link_to(loan.name, loan) %>
        </td>
        <td class="align_center">
          <%= link_to(loan.contact_no, loan) %>
        </td>
        <td class="align_center">
          <%= loan.email %>
        </td>
        <td class="align_center">
          <%= loan.profession %>
        </td>
        <td class="align_center">
          <%= loan.salary %>
        </td>
        <td class="align_center">
          <%= loan.obligation %>
        </td>
        <td class="align_center">
          <%= link_to(loan.status, loan) %>
        </td>
        <td class="align_center">
          <%= link_to(loan.loan_amount, loan) %>
        </td>
        <td class="align_center">
          <%= truncate(loan.remarks, :length => 10) %>
        </td>
        <td>
          <%= link_to 'Edit', edit_loan_path(loan) %>
          <%#= link_to 'Edit', edit_loan_path(loan),class: "btn btn-outline-primary btn-md" %>
          <%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>

      <% if @loans.empty? %>
          <div class="align_center">
            <span class="no_record"><%= " No Records Found.."%></span>
          </div>
      <% end %>
</div>
<div class="flickr_pagination pagination-margin">
  <%= will_paginate @loans, container: false %>
</div>


<style>
  
  .no_record{
    color: red;
  }
</style>

app/views/loans/create.js.erb
toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": false,
  "positionClass": "toast-top-full-width",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "100",
  "hideDuration": "5000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
<% if @loan_created.errors.empty? %>
  $('.finance_form')[0].reset();
  $('#ModalAddFinance').modal('hide');
    toastr["success"]('New Lead has been successfully Created.')
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_invoice').append('<p class = "error_msg" ><%= @loan_created.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%#= render 'form2', loan: @loan %>

<%= form_for @loan do |f| %>
  

  <div class="form-group row">
    <%= f.label :name, "Customer Name:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :contact_no, "Contact No:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :contact_no, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
   <%= f.label :email, "Email:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :email, required: true, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :loan_amount, "Loan Amount:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :loan_amount, required: true, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :salary, "Salary:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.number_field :salary, required: true, class: 'form-control', min: 0 %>
   </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :obligation, "Obligation:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :obligation, required: true, class: 'form-control' %>
   </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :profession, "Profession:", class: "col-4 col-form-label" %>
   <% profession = ['Self emp1', 'Self emp2']%>
   <div class="col-8">
     <%= f.select :profession, profession, required: true, class: 'form-control', :include_blank => true, selected: true %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :status, "Status:", class: "col-4 col-form-label" %>
   <% status = ['Opened','Closed','Follow Up']%>
   <div class="col-8">
    <%= select_tag :status,  options_from_collection_for_select(Loan::ENUM_ENTITY, :last, :first ), { :include_blank => true, selected: true} %>
      <%#= f.select :pstatus, status, required: true, class: 'form-control', prompt: "select" %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :remarks, "Remarks:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_area :remarks, required: true, class: 'form-control' %>
   </div>
  </div>


  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary pull-right'  %>
  </div>

<% end %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<%#= link_to 'New Loan', new_loan_path %>
<div class="container">
  <%= render "loans/action_button" %>
  <br>
  <%= render "loans/table" %>
</div>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<h2>Show Lead:</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @loan.name %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @loan.contact_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @loan.email %>
</p>

<p>
  <strong>Loan amount:</strong>
  <%= @loan.loan_amount %>
</p>

<p>
  <strong>status:</strong>
  <%= @loan.status %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @loan.profession %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @loan.salary %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @loan.remarks %>
</p>

<p>
  <strong>Obligation:</strong>
  <%= @loan.obligation %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan), class: "btn btn-outline-success btn-md" %> |
<%= link_to 'Back', loans_path, class: "btn btn-outline-info btn-md" %>