config/routes.rb
Rails.application.routes.draw do

  get 'homes/index'
  get '/thankyou', to: "feedbacks#thankyou"
  get '/thank_you', to: "housing_rentals#thank_you"

  devise_for :users, skip: :registrations
  resources :housing_rentals
  resources :loans
  resources :feedbacks

  resources :loans do
    collection { post :import }
  end

  authenticate :user do
    resources :feedbacks, only: [:index, :edit, :update, :destroy]
  end
  root "loans#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/housing_rental.rb
class HousingRental < ApplicationRecord
end

app/controllers/housing_rentals_controller.rb
class HousingRentalsController < ApplicationController

  before_action :authenticate_user!, :except => [:new, :create, :thank_you]
  def index
    housings = HousingRental.all
    @housings = housings.paginate(page: params[:page]).order("created_at DESC").per_page(5)
      respond_to do |format|
        format.html
        format.csv {send_data @feedbacks.to_csv(['name', 'contact', 'society_name', 'block', 'flat_no', 'bedroom', 'square_feet', 'rental_amt', 'deposit', 'negotiable', 'site_visit', 'remarks'])}
      end
  end

  def new
  	@housing = HousingRental.new
  end

  def create
  	@housing = HousingRental.new(housing_params)
    respond_to do |format|
      if @housing.save
        format.json {render json: @housing, status: :created}
        format.js
        format.html {redirect_to thank_you_path, flash: {success: "Your rental was successfully updated."}}
        else
        format.json {render json: @housing.errors.full_messages, status: :unprocessable_entity}
        format.js
        format.html {render "new", flash: {error: @housing.errors.full_messages}}
        end
    end
  end

  def edit
    @housing = HousingRental.find(params[:id])
  end

  def show
    @housing = HousingRental.find(params[:id])
  end

  def destroy
    @housing = HousingRental.find(params[:id])
    @housing.destroy
    respond_to do |format|
      format.html { redirect_to housing_rentals_path, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    @housing = HousingRental.find(params[:id])
    if @housing.update(housing_params)
      flash[:notice] = "updated successfully.."
      redirect_to housing_rentals_path
    else
      flash[:notice] = "Something went wrong.."
      render :edit
    end
  end

  def thank_you ;end
end


private

  def housing_params
  	params.require(:housing_rental).permit(:name, :contact, :society_name, :block, :flat_no, :bedroom, :square_feet, :rental_amt, :deposit, :negotiable, :site_visit, :remarks)
  end

app/helpers/housing_rentals_helper.rb
module HousingRentalsHelper
end

app/views/housing_rentals/_action_button.html.erb
<div class="row action-button-margins">
    <div class="col-md-2">
      <%= link_to "New Housing", new_housing_rental_path, class: "btn btn-outline-primary"%>
    </div>
  
    <div class="col-md-2">
       <%= form_tag import_loans_path, multipart: true, class: 'form-inline' do %>
        <div class="form-group">
          <%= link_to "Export CSV", loans_path(format: "csv"), class: 'btn btn-outline-success btn-md' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-10">
      <div class="full-left">
        <% if user_signed_in?%>
          <span class="user"><%= current_user.email %></span> |
              <%#= link_to "Change Password", edit_user_registration_path %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <% end %>
      </div>
    </div>


</div>


<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Loan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%#= render "form2" %>
      </div>
    </div>
  </div>
</div>



<style type="text/css">
  ul {list-style: none;padding: 0px;margin: 0px;}
  ul li {display: block;position: relative;float: left;border:1px solid #fff}
  li ul {display: none;}
  ul li a {display: block;background: #fff;padding: 5px 10px 5px 10px;text-decoration: none;
           white-space: nowrap;color: #fff;}
  ul li a:hover {background: #fff;}
  li:hover ul {display: block; position: absolute;}
  li:hover li {float: none;}
  li:hover a {background: #b9b9b9;}
  li:hover li a:hover {background: #0275d8;}
  #drop-nav li ul li {border-top: 0px;}
  .email{
    padding-top: 1%;
  }
  .hi{
    color: black;
    background-color: #94a294;
  }
  .user{
    background-color: orange;
    font-size: 20px;

  }
  .full-left{
        width: 99%;
    float: right;
    margin-top: -8%;
}
  }
</style>









<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
        if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
        } else {
            a[i].style.display = "none";
        }
    }
}
</script>




<style type="text/css">
  <style>
#dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

#dropbtn:hover, #dropbtn:focus {
    background-color: #3e8e41;
}

#myInput {
    border-box: box-sizing;
    background-image: url('searchicon.png');
    background-position: 14px 12px;
    background-repeat: no-repeat;
    font-size: 16px;
    padding: 14px 20px 12px 45px;
    border: none;
    border-bottom: 1px solid #ddd;
}

#myInput:focus {outline: 3px solid #ddd;}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f6f6f6;
    min-width: 230px;
    overflow: auto;
    border: 1px solid #ddd;
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>
</style>

app/views/housing_rentals/_form.html.erb
<h3 class="text-center header-color"><span class="fa fa-home"></span> <%#= image_tag('house-search') %>Your Rental Agent</h3> 

</br>
<%= form_for @housing, :html => { :multipart => true } do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Owner Name:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, required: true, class: 'form-control', placeholder: "your name" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :contact, "Contact No:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.number_field :contact, required: true, :maxlength => 10, class: 'form-control', placeholder: "ex. 12345678990" %>
    </div>
  </div>

  <div class="form-group row">
   <%= f.label :society_name, "Society Name:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :society_name, class: 'form-control', required: true %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :block, "Block:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :block, class: 'form-control', required: true %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :flat_number, "Flat No:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :flat_no, class: 'form-control', required: true %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :square_feet, "Sqr Feet / Bedroom", class: "col-4 col-form-label" %>
   <div class="col-4">
     <%= f.text_field :square_feet, required: true, class: 'form-control'%>
   </div>
    <div class="col-2 select ">
     <%= f.select :bedroom, ["1 RK", "1 BHK", "2 BHK", "3 BHK", "4 BHK"], required: true, class: 'form-control', prompt: "select" %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :negotiable, "Negotiable / Site Visit:", class: "col-4 col-form-label" %>
   <div class="col-4">
     <%= f.select :negotiable, ['Yes', 'No'], required: true, class: 'form-control', prompt: "select" %>
   </div>
   <div class="col-2 select">
     <%= f.select :site_visit,["Yes", "No"], required: true, class: 'form-control', prompt: "select" %>
   </div>
  </div>

  <div class="form-group row">
      <%= f.label :rental_amt, "Rental Price / Deposit Amt", class: "col-4 col-form-label" %>
      <div class="col-4">
        <%= f.number_field :rental_amt, required: true, class: 'form-control' %>
      </div>
       <div class="col-4">
         <%= f.number_field :deposit, required: true, class: 'form-control' %>
       </div>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :remarks, "Remarks:", class: "col-4 col-form-label" %>
   <div class="col-8 remarks-style">
     <%= f.text_area :remarks, required: true, class: 'form-control'%>
   </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: 'btn pull-right btn-color'  %>
  </div>
<% end %>






<style type="text/css">
  body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 94vh;
  background: #FDD900;
}
h1 {
  margin: 0 0 0.25em;
}
/* Reset Select */
select {
  -webkit-appearance: none;
  -moz-appearance: none;
  -ms-appearance: none;
  appearance: none;
  outline: 0;
  box-shadow: none;
  border: 0 !important;
  background: #2c3e50;
  background-image: none;
}
/* Remove IE arrow */
select::-ms-expand {
  display: none;
}
/* Custom Select */
#housing_rental_bedroom,
#housing_rental_site_visit,
#housing_rental_negotiable {
  position: relative;
  display: flex;
  width: 7em;
  height: 3em;
  line-height: 3;
  background: #ffffff;
  overflow: hidden;
  border-radius: .25em;
}
select {
  flex: 1;
  padding: 0 .5em;
  color: #999;
  cursor: pointer;
}
/* Arrow */
#housing_rental_bedroom::after,
#housing_rental_site_visit::after,
#housing_rental_negotiable::after {
  content: '\25BC';
  position: absolute;
  top: 0;
  right: 0;
  padding: 0 1em;
  background: #34495e;
  cursor: pointer;
  pointer-events: none;
  -webkit-transition: .25s all ease;
  -o-transition: .25s all ease;
  transition: .25s all ease;
}
/* Transition */
#housing_rental_bedroom:hover::after,
#housing_rental_site_visit:hover::after,
#housing_rental_negotiable:hover::after {
  color: #f39c12;
}
.remarks-style {
  width: 280px;
}
</style>

app/views/housing_rentals/_table.html.erb
<div class="table_invoice">
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr class="bg-primary">
        <th class="align_center">Name</th>
        <th class="align_center">Contact No</th>
        <th class='align_center'>Socity Name</th>
        <th class='align_center'>Block</th>
        <th class='align_center'>Flat number</th>
        <th class='align_center'>Square Feet</th>
        <th class='align_center'>Bedroom </th>
        <th class="align_center">Negotiable</th>
        <th class="align_center">Site Visit</th>
        <th class="align_center">Rental Amt</th>
        <th class="align_center">Deposit</th>
        <th class='align_center'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @housings.each do |feedback| %>
      <tr>
        <td class="align_center">
          <%= truncate(feedback.name, length: 20) %>
        </td>
        <td class="align_center">
          <%= feedback.contact %>
        </td>
        <td class="align_center">
          <%= truncate(feedback.society_name, length: 20) %>
        </td>
        <td class="align_center">
          <%= feedback.block %>
        </td>
        <td class="align_center">
          <%= truncate(feedback.flat_no, length: 20) %>
        </td>
        <td class="align_center">
          <%= feedback.square_feet %>
        </td>
        <td class="align_center">
          <%= feedback.bedroom %>
        </td>
         <td class="align_center">
          <%= feedback.negotiable %>
        </td>
         <td class="align_center">
          <%= feedback.site_visit %>
        </td>
         <td class="align_center">
          <%= feedback.rental_amt %>
        </td>
         <td class="align_center">
          <%= feedback.deposit %>
        </td>
        <td class="col-4">
          <%= link_to 'Edit', edit_housing_rental_path(feedback) %>
          <%= link_to 'Show', housing_rental_path(feedback),class: "btn btn-outline-primary btn-md" %>
          <%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>

      <% if @housings.empty? %>
          <div class="align_center">
            <span class="no_record"><%= " No Records Found.."%></span>
          </div>
      <% end %>
</div>
<div class="flickr_pagination pagination-margin">
  <%= will_paginate @housings, container: false %>
</div>


<style>
  
  .no_record{
    color: red;
  }
</style>

app/views/housing_rentals/create.html.erb
<h1>HousingRentals#create</h1>
<p>Find me in app/views/housing_rentals/create.html.erb</p>

app/views/housing_rentals/edit.html.erb
<%= render "form"%>

app/views/housing_rentals/index.html.erb
<div class="container">
  <%= render "housing_rentals/action_button" %>
  <br>
  <%= render "housing_rentals/table" %>
</div>

app/views/housing_rentals/new.html.erb
<%= render "form"%>

app/views/housing_rentals/show.html.erb
<h2>House Info:</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @housing.name %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @housing.contact %>
</p>

<p>
  <strong>Society name: </strong>
  <%= @housing.society_name %>
</p>

<p>
  <strong>Block: </strong>
  <%= @housing.block %>
</p>

<p>
  <strong>Flat No: </strong>
  <%= @housing.flat_no %>
</p>

<p>
  <strong>Bedroom: </strong>
  <%= @housing.bedroom %>
</p>

<p>
  <strong>Square Feet: </strong>
  <%= @housing.square_feet %>
</p>

<p>
  <strong>Rental Amt: </strong>
  <%= @housing.rental_amt %>
</p>

<p>
  <strong>Deposit: </strong>
  <%= @housing.deposit %>
</p>

<p>
  <strong>Negotiable: </strong>
  <%= @housing.negotiable %>
</p>

<p>
  <strong>Site Visit: </strong>
  <%= @housing.site_visit %>
</p>

<p>
  <strong>Remarks: </strong>
  <%= @housing.remarks %>
</p>

<%= link_to 'Edit', edit_housing_rental_path(@housing), class: "btn btn-outline-success btn-md" %> |
<%= link_to 'Back', housing_rentals_path, class: "btn btn-outline-info btn-md" %>
   

app/views/housing_rentals/thank_you.html.erb
<h1 class="feedback">Thank you have a nice day... </h1>