config/routes.rb
Rails.application.routes.draw do

  get 'homes/index'
  get '/thankyou', to: "feedbacks#thankyou"
  get '/thank_you', to: "housing_rentals#thank_you"

  devise_for :users, skip: :registrations
  resources :housing_rentals
  resources :loans
  resources :feedbacks

  resources :loans do
    collection { post :import }
  end

  authenticate :user do
    resources :feedbacks, only: [:index, :edit, :update, :destroy]
  end
  root "loans#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
	has_many :references, dependent: :destroy
	accepts_nested_attributes_for :references, :allow_destroy => true

  def self.to_csv(fields = column_names, options = {})
    CSV.generate(options) do |csv|
      csv << fields
      all.each do |feedback|
        csv << feedback.attributes.values_at(*fields)
      end
    end
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_action :authenticate_user!, :except => [:new, :create, :thankyou]
  def index
    feedbacks = Feedback.all
    @feedbacks = feedbacks.paginate(page: params[:page]).order("created_at DESC").per_page(5)
      respond_to do |format|
        format.html
        format.csv {send_data @feedbacks.to_csv(['name', 'contact_no', 'socity', 'block', 'flat_number', 'product_feedback', 'executive_feedback'])}
      end
  end

  def new
  	@feedback = Feedback.new
  end

  def create
  	@feedback = Feedback.new(feedback_params)
    respond_to do |format|
      if @feedback.save
        format.json {render json: @feedback, status: :created}
        format.js
        format.html {redirect_to thankyou_path, flash: {success: "Loan was successfully created."}}
        else
        format.json {render json: @feedback.errors.full_messages, status: :unprocessable_entity}
        format.js
        format.html {render "new", flash: {error: @feedback.errors.full_messages}}
        end
    end
  end

  def thankyou
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def update
    @feedback = Feedback.find(params[:id])
    if @feedback.update(feedback_params)
      flash[:notice] = "Feedback was Update successfully"
      redirect_to feedbacks_path
      # format.html { redirect_to feedbacks_path, notice: 'Feedback was successfully updated.'}
      # format.json { render :show, status: :ok, location: @feedback }
    else
      format.html { render :edit }
      format.json { render json: @feedback.errors, status: :unprocessable_entity }
    end
  end


  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_path, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def feedback_params
  	params.require(:feedback).permit(:name, :contact, :society, :block, :flat_number, :product_feedback, :executive_feedback, references_attributes: [:id, :contact_no, :_destroy])
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_action_button.html.erb
<div class="row action-button-margins">
    <div class="col-md-2">
      <%= link_to "New Feedback", new_feedback_path, class: "btn btn-outline-primary"%>
    </div>
  
    <div class="col-md-2">
       <%= form_tag import_loans_path, multipart: true, class: 'form-inline' do %>
        <div class="form-group">
          <%= link_to "Export CSV", loans_path(format: "csv"), class: 'btn btn-outline-success btn-md' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-10">
      <div class="full-left">
        <% if user_signed_in?%>
          <span class="user"><%= current_user.email %></span> |
              <%#= link_to "Change Password", edit_user_registration_path %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        <% end %>
      </div>
    </div>


</div>


<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Loan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%#= render "form2" %>
      </div>
    </div>
  </div>
</div>



<style type="text/css">
  ul {list-style: none;padding: 0px;margin: 0px;}
  ul li {display: block;position: relative;float: left;border:1px solid #fff}
  li ul {display: none;}
  ul li a {display: block;background: #fff;padding: 5px 10px 5px 10px;text-decoration: none;
           white-space: nowrap;color: #fff;}
  ul li a:hover {background: #fff;}
  li:hover ul {display: block; position: absolute;}
  li:hover li {float: none;}
  li:hover a {background: #b9b9b9;}
  li:hover li a:hover {background: #0275d8;}
  #drop-nav li ul li {border-top: 0px;}
  .email{
    padding-top: 1%;
  }
  .hi{
    color: black;
    background-color: #94a294;
  }
  .user{
    background-color: orange;
    font-size: 20px;

  }
  .full-left{
        width: 99%;
    float: right;
    margin-top: -8%;
}
  }
</style>









<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    div = document.getElementById("myDropdown");
    a = div.getElementsByTagName("a");
    for (i = 0; i < a.length; i++) {
        if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
        } else {
            a[i].style.display = "none";
        }
    }
}
</script>




<style type="text/css">
  <style>
#dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

#dropbtn:hover, #dropbtn:focus {
    background-color: #3e8e41;
}

#myInput {
    border-box: box-sizing;
    background-image: url('searchicon.png');
    background-position: 14px 12px;
    background-repeat: no-repeat;
    font-size: 16px;
    padding: 14px 20px 12px 45px;
    border: none;
    border-bottom: 1px solid #ddd;
}

#myInput:focus {outline: 3px solid #ddd;}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f6f6f6;
    min-width: 230px;
    overflow: auto;
    border: 1px solid #ddd;
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>
</style>

app/views/feedbacks/_form.html.erb
<h3 style="color: #6d716d;" class="text-center">Customer Feedback</h3>
</br>
<%= form_for @feedback, :html => { :multipart => true } do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Customer Name:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :contact, "Contact No:", class: "col-4 col-form-label" %>
    <div class="col-8">
      <%= f.number_field :contact, required: true, :maxlength => 10, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
   <%= f.label :society, "Society:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :society, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :block, "Block:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :block, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%= f.label :flat_number, "Flat Number:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :flat_number, class: 'form-control', min: 0 %>
   </div>
  </div>
  
  <div class="form-group row">
   <%= f.label :product_feedback, "Product Feedback:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_area :product_feedback, required: true, class: 'form-control' %>
   </div>
  </div>

   <div class="form-group row">
   <%= f.label :executive_feedback, "Executive Feedback:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_area :executive_feedback, required: true, class: 'form-control' %>
   </div>
  </div>

  <div class="form-group row">
   <%#= f.label :executive_feedback, "Executive Feedback:", class: "col-4 col-form-label" %>
    <%= link_to_add_association f, :references do %>
     	<strong style="color: red">Add Reference No</strong>
     <% end %>
   <div class="col-4">
     <%= f.fields_for :references do |rf| %>
     	<% render 'reference_fields', f: rf %>
     <% end %>
   </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary pull-right'  %>
  </div>

<% end %>

app/views/feedbacks/_reference_fields.html.erb
<div class="form-group row">
   <%= f.label :contact_no, "Contact No:", class: "col-4 col-form-label" %>
   <div class="col-8">
     <%= f.text_field :contact_no, required: true, class: 'form-control' %>
   </div>
</div>

app/views/feedbacks/_table.html.erb
<div class="table_invoice">
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr class="bg-primary">
        <th class="align_center">Name</th>
        <th class="align_center">Contact No</th>
        <th class='align_center'>Socity</th>
        <th class='align_center'>Block</th>
        <th class='align_center'>Flat number</th>
        <th class='align_center'>Product Feedback</th>
        <th class='align_center'>Executive Feedback</th>
        <th class='align_center'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @feedbacks.each do |feedback| %>
      <tr>
        <td class="align_center">
          <%= feedback.name %>
        </td>
        <td class="align_center">
          <%= feedback.contact %>
        </td>
        <td class="align_center">
          <%= feedback.society %>
        </td>
        <td class="align_center">
          <%= feedback.block %>
        </td>
        <td class="align_center">
          <%= feedback.flat_number %>
        </td>
        <td class="align_center">
          <%= feedback.product_feedback %>
        </td>
        <td class="align_center">
          <%= feedback.executive_feedback %>
        </td>
        <td>
          <%= link_to 'Edit', edit_feedback_path(feedback) %>
          <%#= link_to 'Edit', edit_feedback_path(feedback),class: "btn btn-outline-primary btn-md" %>
          <%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>

      <% if @feedbacks.empty? %>
          <div class="align_center">
            <span class="no_record"><%= " No Records Found.."%></span>
          </div>
      <% end %>
</div>
<div class="flickr_pagination pagination-margin">
  <%= will_paginate @feedbacks, container: false %>
</div>


<style>
  
  .no_record{
    color: red;
  }
</style>

app/views/feedbacks/edit.html.erb
<%= render "feedbacks/form"%>

app/views/feedbacks/index.html.erb
<div class="container">
  <%= render "feedbacks/action_button" %>
  <br>
  <%= render "feedbacks/table" %>
</div>

app/views/feedbacks/thankyou.html.erb
<h1 class="feedback">Thank you for yor valuable feedback</h1>